package co.simplon.livrokaz.model;
// Generated 14 janv. 2019 à 21:06:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CommandLine generated by hbm2java
 */
@Entity
@Table(name = "command_line", catalog = "livrokaz")
public class CommandLine implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private Integer clId;
	private Book book;
	private int clQuantity;
	private Orders orders;
	private Date date;
	private boolean status;
	private Customer customer;

	public CommandLine() {
	}

	/**
	 * @return the customer
	 */
	//@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name= "cu_id", nullable = false)
	public Customer getCustomer() {
		return customer;
	}

	/**
	 * @param customer the customer to set
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * @return the status
	 */
	@Column(name = "cl_status", nullable = false)
	public boolean isStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}

	/**
	 * @return the date
	 */
	@Column(name = "cl_date", nullable = false)
	public Date getDate() {
		return date;
	}

	/**
	 * @param date the date to set
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	public CommandLine(Book book, int clQuantity) {
		this.book = book;
		this.clQuantity = clQuantity;
	}

	public CommandLine(Book book, int clQuantity, Orders orderses) {
		this.book = book;
		this.clQuantity = clQuantity;
		this.orders = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cl_id", unique = true, nullable = false)
	public Integer getClId() {
		return this.clId;
	}

	public void setClId(Integer clId) {
		this.clId = clId;
	}
	//@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bo_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@Column(name = "cl_quantity", nullable = false)
	public int getClQuantity() {
		return this.clQuantity;
	}

	public void setClQuantity(int clQuantity) {
		this.clQuantity = clQuantity;
	}
	
	
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "or_id", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

}
