package co.simplon.livrokaz.model;
// Generated 9 févr. 2019 14:27:59 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommandLine generated by hbm2java
 */
@Entity
@Table(name = "command_line", catalog = "livrokaz")
public class CommandLine implements java.io.Serializable {

	private Integer clId;
	private Book book;
	private Customer customer;
	private Orders orders;
	private int clQuantity;
	private boolean clStatus;
	private Date clDate;

	public CommandLine() {
	}

	public CommandLine(Book book, Customer customer, int clQuantity, boolean clStatus, Date clDate) {
		this.book = book;
		this.customer = customer;
		this.clQuantity = clQuantity;
		this.clStatus = clStatus;
		this.clDate = clDate;
	}

	public CommandLine(Book book, Customer customer, Orders orders, int clQuantity, boolean clStatus, Date clDate) {
		this.book = book;
		this.customer = customer;
		this.orders = orders;
		this.clQuantity = clQuantity;
		this.clStatus = clStatus;
		this.clDate = clDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cl_id", unique = true, nullable = false)
	public Integer getClId() {
		return this.clId;
	}

	public void setClId(Integer clId) {
		this.clId = clId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bo_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cu_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "or_id")
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "cl_quantity", nullable = false)
	public int getClQuantity() {
		return this.clQuantity;
	}

	public void setClQuantity(int clQuantity) {
		this.clQuantity = clQuantity;
	}

	@Column(name = "cl_status", nullable = false)
	public boolean isClStatus() {
		return this.clStatus;
	}

	public void setClStatus(boolean clStatus) {
		this.clStatus = clStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cl_date", nullable = false, length = 19)
	public Date getClDate() {
		return this.clDate;
	}

	public void setClDate(Date clDate) {
		this.clDate = clDate;
	}

}
