package co.simplon.livrokaz.model;
// Generated 14 janv. 2019 à 21:06:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "livrokaz")
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cuId;
	private Role role;
	private String cuName;
	private String cuFirstName;
	private String cuInvoiceAddress;
	private String cuDeliveryAddress;
	private String cuPhone;
	private String cuMail;
	private String cuPassword;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Customer() {
	}

	public Customer(Role role, String cuName, String cuFirstName, String cuInvoiceAddress, String cuDeliveryAddress,
			String cuPhone, String cuMail, String cuPassword) {
		this.role = role;
		this.cuName = cuName;
		this.cuFirstName = cuFirstName;
		this.cuInvoiceAddress = cuInvoiceAddress;
		this.cuDeliveryAddress = cuDeliveryAddress;
		this.cuPhone = cuPhone;
		this.cuMail = cuMail;
		this.cuPassword = cuPassword;
	}

	public Customer(Role role, String cuName, String cuFirstName, String cuInvoiceAddress, String cuDeliveryAddress,
			String cuPhone, String cuMail, String cuPassword, Set<Orders> orderses) {
		this.role = role;
		this.cuName = cuName;
		this.cuFirstName = cuFirstName;
		this.cuInvoiceAddress = cuInvoiceAddress;
		this.cuDeliveryAddress = cuDeliveryAddress;
		this.cuPhone = cuPhone;
		this.cuMail = cuMail;
		this.cuPassword = cuPassword;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cu_id", unique = true, nullable = false)
	public Integer getCuId() {
		return this.cuId;
	}

	public void setCuId(Integer cuId) {
		this.cuId = cuId;
	}
	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ro_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "cu_name", nullable = false, length = 50)
	public String getCuName() {
		return this.cuName;
	}

	public void setCuName(String cuName) {
		this.cuName = cuName;
	}

	@Column(name = "cu_first_name", nullable = false, length = 50)
	public String getCuFirstName() {
		return this.cuFirstName;
	}

	public void setCuFirstName(String cuFirstName) {
		this.cuFirstName = cuFirstName;
	}

	@Column(name = "cu_invoice_address", nullable = false, length = 65535)
	public String getCuInvoiceAddress() {
		return this.cuInvoiceAddress;
	}

	public void setCuInvoiceAddress(String cuInvoiceAddress) {
		this.cuInvoiceAddress = cuInvoiceAddress;
	}

	@Column(name = "cu_delivery_address", nullable = false, length = 65535)
	public String getCuDeliveryAddress() {
		return this.cuDeliveryAddress;
	}

	public void setCuDeliveryAddress(String cuDeliveryAddress) {
		this.cuDeliveryAddress = cuDeliveryAddress;
	}

	@Column(name = "cu_phone", nullable = false, length = 50)
	public String getCuPhone() {
		return this.cuPhone;
	}

	public void setCuPhone(String cuPhone) {
		this.cuPhone = cuPhone;
	}

	@Column(name = "cu_mail", nullable = false, length = 50)
	public String getCuMail() {
		return this.cuMail;
	}

	public void setCuMail(String cuMail) {
		this.cuMail = cuMail;
	}

	@Column(name = "cu_password", nullable = false, length = 50)
	public String getCuPassword() {
		return this.cuPassword;
	}

	public void setCuPassword(String cuPassword) {
		this.cuPassword = cuPassword;
	}
	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
