package co.simplon.livrokaz.model;
// Generated 14 janv. 2019 à 21:06:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "livrokaz")
public class Orders implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer orId;
	private Customer customer;
	private Date orDate;
	private boolean orCompleted;
	private float orShippingCosts;
	private float orTotalCost;
	private Set<CommandLine> commandLines = new HashSet<CommandLine>(0);

	public Orders() {
	}

	public Orders(Customer customer, Date orDate, boolean orCompleted, float orShippingCosts, float orTotalCost) {
		this.customer = customer;
		this.orDate = orDate;
		this.orCompleted = orCompleted;
		this.orShippingCosts = orShippingCosts;
		this.orTotalCost = orTotalCost;
	}

	public Orders(Customer customer, Date orDate, boolean orCompleted, float orShippingCosts, float orTotalCost,
			Set<CommandLine> commandLines) {
		this.customer = customer;
		this.orDate = orDate;
		this.orCompleted = orCompleted;
		this.orShippingCosts = orShippingCosts;
		this.orTotalCost = orTotalCost;
		this.commandLines = commandLines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "or_id", unique = true, nullable = false)
	public Integer getOrId() {
		return this.orId;
	}

	public void setOrId(Integer orId) {
		this.orId = orId;
	}
	//@JsonManagedReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cu_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "or_date", nullable = false, length = 10)
	public Date getOrDate() {
		return this.orDate;
	}

	public void setOrDate(Date orDate) {
		this.orDate = orDate;
	}

	@Column(name = "or_completed", nullable = false)
	public boolean isOrCompleted() {
		return this.orCompleted;
	}

	public void setOrCompleted(boolean orCompleted) {
		this.orCompleted = orCompleted;
	}

	@Column(name = "or_shipping_costs", nullable = false, precision = 12, scale = 0)
	public float getOrShippingCosts() {
		return this.orShippingCosts;
	}

	public void setOrShippingCosts(float orShippingCosts) {
		this.orShippingCosts = orShippingCosts;
	}

	@Column(name = "or_total_cost", nullable = false, precision = 12, scale = 0)
	public float getOrTotalCost() {
		return this.orTotalCost;
	}

	public void setOrTotalCost(float orTotalCost) {
		this.orTotalCost = orTotalCost;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<CommandLine> getCommandLines() {
		return this.commandLines;
	}

	public void setCommandLines(Set<CommandLine> commandLines) {
		this.commandLines = commandLines;
	}

}
