package co.simplon.livrokaz.model;
// Generated 14 janv. 2019 à 21:06:11 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "livrokaz")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer roId;
	private String roLabel;
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<Employees> employeeses = new HashSet<Employees>(0);

	public Role() {
	}

	public Role(String roLabel) {
		this.roLabel = roLabel;
	}

	public Role(String roLabel, Set<Customer> customers, Set<Employees> employeeses) {
		this.roLabel = roLabel;
		this.customers = customers;
		this.employeeses = employeeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ro_id", unique = true, nullable = false)
	public Integer getRoId() {
		return this.roId;
	}

	public void setRoId(Integer roId) {
		this.roId = roId;
	}

	@Column(name = "ro_label", nullable = false, length = 50)
	public String getRoLabel() {
		return this.roLabel;
	}

	public void setRoLabel(String roLabel) {
		this.roLabel = roLabel;
	}

	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}
	@JsonManagedReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Employees> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<Employees> employeeses) {
		this.employeeses = employeeses;
	}

}
