package co.simplon.livrokaz.model;
// Generated 14 janv. 2019 à 21:06:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;


/**
 * Style generated by hbm2java
 */
@Entity
@Table(name = "style", catalog = "livrokaz")
public class Style implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer stId;
	private String stLabelFr;
	private String stLabelEn;
	private Set<Book> books = new HashSet<Book>(0);

	public Style() {
	}

	public Style(String stLabelFr, String stLabelEn) {
		this.stLabelFr = stLabelFr;
		this.stLabelEn = stLabelEn;
	}

	public Style(String stLabelFr, String stLabelEn, Set<Book> books) {
		this.stLabelFr = stLabelFr;
		this.stLabelEn = stLabelEn;
		this.books = books;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "st_id", unique = true, nullable = false)
	public Integer getStId() {
		return this.stId;
	}

	public void setStId(Integer stId) {
		this.stId = stId;
	}

	@Column(name = "st_label_fr", nullable = false, length = 50)
	public String getStLabelFr() {
		return this.stLabelFr;
	}

	public void setStLabelFr(String stLabelFr) {
		this.stLabelFr = stLabelFr;
	}

	@Column(name = "st_label_en", nullable = false, length = 50)
	public String getStLabelEn() {
		return this.stLabelEn;
	}

	public void setStLabelEn(String stLabelEn) {
		this.stLabelEn = stLabelEn;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "style")
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
